[helpers]

[default]
depends = []

[nvim.files]
nvim = "~/.config/nvim"

[tmux.files]
tmux = "~/.tmux.conf"

[zsh.files]
zshrc = "~/.zshrc"

[zsh.variables]
projectsdir = "dev/"

[gitconfig.files]
gitconfig = "~/.gitconfig"

[gitconfig.variables]
username = "bker"
